models/solicitud_trabajo_grado.go
models/trabajo_grado.go

#21572# Campo periodo academico

---

controllers/tr_respuesta_solicitud.go
controllers/tr_solicitud.go
controllers/tr_trabajo_grado.go
lastupdate.tmp
models/tr_registrar_nota.go
models/tr_registrar_respuestas_solicitudes.go
models/tr_respuesta_solicitud.go
models/tr_solicitud.go
models/tr_trabajo_grado.go
routers/commentsRouter_________________________udistrital_Polux_API_Crud_controllers.go
swagger/swagger.json
swagger/swagger.yml

#22634# Se verifica documentación y se hacen algunos ajustes

---

.gitignore
lastupdate.tmp
models/vinculacion_trabajo_grado.go

Code karianov

---

models/tr_respuesta_solicitud.go

Se actualiza la vinculación de una revisión cuando se aprueba la solicitud de cambio de vinculado de un trabajo de grado

#24980# Actualizar vinculación a la que se asocia una revisión

---

.drone.yml

Se coloco todo los dos pasos de drone para el migration y rollback en el archivo de drone-yml

Fix : Se coloco en comentario migration y rollback en drone

---

database/migrations/20230615_190847_agregar_columna_objetivo.go
database/scripts/20230615_190847_agregar_columna_objetivo_down.sql
database/scripts/20230615_190847_agregar_columna_objetivo_up.sql
models/trabajo_grado.go
swagger/swagger.json
swagger/swagger.yml

Se relaciona con el Issue udistrital/polux_cliente#346

feat: Actualización modelo de base de datos

---

models/tr_respuesta_solicitud.go

feat: Se desarrolla la funcionalidad asociada al tema del cambio de objetivos, ya que se debe de realizar un post en la base de datos

Merge from develop to release/0.0.1

---

controllers/detalle_trabajo_grado.go
database/migrations/20230712_011240_crear_tabla_detalle_trabajo_grado.go
database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_down.sql
database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_up.sql
go.sum
models/detalle_trabajo_grado.go
routers/commentsRouter_controllers.go

- Se desarrolla la migración y demás archivos necesarios para la creación de la nueva tabla llamada detalle_trabajo_grado

feat: udistrital/polux_cliente#346 migrate_detalle_trabajo_grado

---

routers/router.go

feat: Se añade en el archivo router, la ruta que permitirá acceder a los métodos de la nueva tabla

feat: Se añade en el archivo router, la ruta que permitirá acceder a la tabla

---

database/migrations/20230615_190847_agregar_columna_objetivo.go
database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_up.sql

fix: Se corrige la consulta SQL para la creación de la tabla detalle_trabajo_grado y se realiza la corección para la columna de agregar objetivo, con respecto a las importaciones

fix: Se corrige la consulta SQL para la creación de la tabla detalle_trabajo_grado

---

database/migrations/20230615_190847_agregar_columna_objetivo.go
database/scripts/20230712_011240_crear_tabla_detalle_trabajo_grado_up.sql
routers/router.go

fix: Se corrigen archivos de las migraciones y scripts

fix: Se corrigen archivos de las migraciones y scripts

---

models/tr_respuesta_solicitud.go

- Se realiza la corrección en el CRUD para el guardado de los datos de la revista en las solicitudes de revisión de trabajo de grado para la modalidad de articulo académico.

feat: udistrital/polux_cliente#346    Corrección_Revista_y_visualización

---

.gitignore
go.mod
go.sum
models/tr_registrar_nota.go
models/tr_respuesta_solicitud.go
swagger/swagger.json
swagger/swagger.yml

feat: Ajuste de transacciones para materias posgrado

---

models/tr_respuesta_solicitud.go

- Se desarrolla la lógica asociada para guardar los detalles de la pasantía externa en la tabla detalle_trabajo_grado.
- Y la lógica asociada a la prorroga.

feat: udistrital/polux_cliente#397 Correcciones_generales_sobre_polux

---

controllers/estudiante_vinculacion_trabajo_grado.go
models/estudiante_vinculacion_trabajo_grado.go
routers/commentsRouter_controllers.go
swagger/swagger.json
swagger/swagger.yml

udistrital/polux_cliente/issues/632

Feature/ Código de los Dos Estudiantes en Registrar Nota

---

controllers/reporte_general.go
models/reporte_general.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

udistrital/polux_cliente/issues/641

Feature/ Polux Reports

---

controllers/reporte_general.go
controllers/reporte_solicitud.go
models/reporte_solicitud.go
routers/commentsRouter_controllers.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

udistrital/polux_cliente/issues/664

Feature/Reporte Solicitud

---

models/reporte_general.go
models/reporte_solicitud.go

udistrital/polux_cliente/issues/685

feature: Generación de Reportes - Nombre Coordinador

---

models/reporte_general.go
models/reporte_solicitud.go

udistrital/polux_cliente/issues/709

feature: Ajuste de consultas SQL #709

---

controllers/reporte_general.go
controllers/reporte_solicitud.go
models/reporte_general.go
models/reporte_solicitud.go

udistrital/polux_cliente/issues/761

Feature/Response Reports

---

.drone.yml
controllers/revision_trabajo_grado.go
controllers/vinculacion_trabajo_grado.go
models/revision_trabajo_grado.go
models/tr_registrar_revision_tg.go
models/vinculacion_trabajo_grado.go
sonar-project.properties

fix: Se corrigen los errores reportados en las pruebas de carga y seguridad

---

controllers/vinculacion_trabajo_grado.go

fix: Corrección formato fechas 

---

models/solicitud_trabajo_grado.go

Se modifica modelo solicitudTrabajoGrado para data personal arl udistrital/polux_cliente#760

feat: se modifica modelo solicitudTrabajoGrado para data personal arl

---

models/solicitud_trabajo_grado.go

fix: se incluye el nuevo campo DatosPersonalesArl en modelo SolicitudTrabajoGrado udistrital/polux_cliente#799

fix: se incluye el nuevo campo DatosPersonalesArl en modelo SolicitudTrabajoGrado

---

controllers/reporte_general.go
controllers/reporte_solicitud.go

fix: Corrección errores Sonarqube 

---

controllers/documento_trabajo_grado.go
models/documento_trabajo_grado.go

fix: se realizan ajustes para desactivar los documentos anexos en solicitud de revisión proyecto grado https://github.com/udistrital/polux_cliente/issues/808

fix: se realizan ajustes para desactivar los documentos anexos en solicitud de revisión proyecto grado

---

models/vinculacion_trabajo_grado.go

feat: Se agrega funcionalidad para almacenar codigo abreviacion de vinculado

---

controllers/reporte_general.go
controllers/reporte_solicitud.go
models/reporte_general.go
models/reporte_solicitud.go
routers/commentsRouter_controllers.go

feat: Se agregan filtros en Reportes 

---

main.go

https://github.com/udistrital/core_documentacion/issues/285

Se cambia el origen de la carpeta middleware para probarla

---

models/espacio_academico_inscrito.go
models/tr_respuesta_solicitud.go

feat: se almacena nombre carrera posgrado 

---

controllers/estudiante_vinculacion_trabajo_grado.go
models/estudiante_vinculacion_trabajo_grado.go

udistrital/polux_cliente/issues/918

feature: Registrar Nota Asistentes #918
